### ISSUE TITLE
calib3d

### ISSUE THREAD

**Issue by tyler8812** [gabriel-vanzandycke/deepsport#1]
Hi, thanks for your contribution.

I have problem in opening the calib3d hyperlink.
Where can I found the repository or code of 2D to 3D coordinate?

Thanks for your help!

**Comment by gabriel-vanzandycke** [comment]
Pip install calib3d

Best

**Comment by tyler8812** [comment]
@gabriel-vanzandycke Thanks for the replying,

I was wondering how is it possible to transform 2d coordinate to 3d coordinate.
Is there any related works or tutorial you read before?

Thanks for your help~

**Comment by gabriel-vanzandycke** [comment]
You'll find `calib3d` documentation here: https://ispgroupucl.github.io/calib3d/calib3d/
There's a quick how-to in the readme here: https://github.com/ispgroupucl/calib3d

More specifically, if you have a camera whose calibration is described by a `Calib` object, you need to use the `project_3D_to_2D` method of `Calib`.
