### ISSUE TITLE
diameter error

### ISSUE THREAD

**Issue by tyler8812** [gabriel-vanzandycke/deepsport#2]
Hi,

I was wondering how to calculate the diameter error in projection approach ?
How the approach calculate diameter?

Thanks for the contribution.

**Comment by gabriel-vanzandycke** [comment]
Hello! I'm not sure I understand your question. This project estimates the ball diameter (in pixels) from an image patch.

The apparent ball diameter in the image space can be retrieved using calibration data and knowledge of real ball diameter. With [calib3d](https://github.com/ispgroupucl/calib3d) library:
```python
BALL_DIAMETER = 23 # Basketball ball has a 23 centimetres diameter
diameter = calib.compute_length2D(BALL_DIAMETER, point3D) # point3D is the ball 3D position given in the annotation
```

At inference, the estimated 3D localization is retrieved using calibration data and the estimated diameter. With [calib3d](https://github.com/ispgroupucl/calib3d) library:
```python
def compute_point3D(calib: Calib, point2D: Point2D, pixel_size: float, true_size: float):
    """ Computes the 3D coordinates of the 2D point `point2D` detected in an image whose calibration
        is given by `calib`, knowing it's 2D size `pixel_size` in the image space and it's true size
        `true_size` in 3D.
    """
    center = Point2D(calib.Kinv@calib.rectify(point2D).H)             # center expressed in camera coordinates system
    corner = Point2D(calib.Kinv@calib.rectify(point2D+pixel_size).H)  # corner expressed in camera coordinates system
    point3D_c = Point3D(center.H * true_size / (corner.x - center.x)) # scaling in the camera coordinates system
    return calib.R.T@(point3D_c-calib.T)                              # recover real world coordinates system
```

The diameter error is the difference between the predicted diameter and the true diameter.

**Comment by tyler8812** [comment]
Thanks for the reply.
My questions is that I find that there is a comparison of diameter error and projection error in projection approach and diameter approach.
I know that diameter approach is using the calib3D, but how the projection approach calculate diameter?
<img width="366" alt="Screen Shot 2022-08-19 at 6 01 52 PM" src="https://user-images.githubusercontent.com/36752354/185595601-61cfabb4-9b44-43ec-aef6-3aa8407501d6.png">

Thanks for the reply

**Comment by gabriel-vanzandycke** [comment]
Hello,
The figure you share comes from the [Ball 3D Localization](https://openaccess.thecvf.com/content/CVPR2022W/CVSports/html/Van_Zandycke_3D_Ball_Localization_From_a_Single_Calibrated_Image_CVPRW_2022_paper.html) paper.
It compares two approaches for annotating ball 3D coordinates in a single calibrated image. And it shows that the "projection approach" has a lower error and lower biais. For more detail, I suggest you give a more thorough read of the paper.

That comparison is not related to this repository in which ball 3D localization is given as ground-truth.

**Comment by tyler8812** [comment]
Hi, @gabriel-vanzandycke 
Thanks for your reply and contribution.
It helps a lot to me!!!
